#!/usr/bin/perl -w

if ($#ARGV < 0) {
	print "USAGE: $0 <input.tex>\n";
	exit 1;
}

my $in = $ARGV[0];

my $pdf = $in;
$pdf =~ s/\.tex$/.pdf/;

my $out = $in;
$out =~ s/\.tex$/.d/;

open(OUT, ">", $out);
open(IN, "<", $in);
while (<IN>) {
	while (/^[^%]*\\includegraphics(?:\[.*?\])?\{(.+?)\}/g) {
		print OUT "$pdf: $1\n";
	}
}
